### ISSUE TITLE
Trying to match 7.3.0-beta3 against range >7.2.7 fails

### ISSUE THREAD

**Issue by akuryan** [adamreeve/semver.net#1]
Trying to match 7.3.0-beta3 against range >7.2.7 fails, while, as far as I understand, it shall return true.
Or, maybe I am missing something very obvious?

```
public class PreReleaseRanges
{
    [Theory]
    [InlineData(">7.2.7", "7.3.0-beta3")]
    public void MatchingPreRelease(string rangeString, string versionString)
    {
        var range = new Range(rangeString);
        var version = new Version(versionString);
        Assert.True(range.IsSatisfied(version));
    }
```

}

**Comment by adamreeve** [comment]
Pre-release versions will never satisfy a range unless the range specifies a pre-release for the matching version. This is because if I specify that i want to use versions `>7.2.7`, I don't usually want to get unstable pre-release versions.

Eg. `7.3.0-beta3` will satisfy `>7.3.0-beta1`, but not `>7.2.7` or `>7.2.7-beta1`.

`new Version("7.3.0-beta3") > new Version("7.2.7")` should return true though.

This matches the behaviour of node-semver, see https://github.com/npm/node-semver#prerelease-tags and https://github.com/adamreeve/semver.net#pre-release-versions

**Comment by akuryan** [comment]
Thanks for clarification
